from __future__ import annotations

import hashlib
import shlex
import subprocess
from pathlib import Path
from typing import Optional

from cluster_dispatch.config import CONFIG_DIR, ProjectConfig, TargetConfig

SSH_DIR_NAME = "ssh"
SSH_CONFIG_NAME = "config"
SSH_CONNECT_TIMEOUT = 20
SSH_CONTROL_PERSIST = "10m"
SSH_CONTROL_SOCKET_ROOT = Path("/tmp/cluster-dispatch-ssh")


def is_local_transport(transport: str, host: str) -> bool:
    normalized_host = host.strip().lower()
    return transport.strip().lower() == "local" or normalized_host in {"", "localhost", "127.0.0.1", "::1"}


def ssh_dir(project_root: Path) -> Path:
    return project_root / CONFIG_DIR / SSH_DIR_NAME


def ssh_config_path(project_root: Path) -> Path:
    return ssh_dir(project_root) / SSH_CONFIG_NAME


def control_socket_path(host: str) -> str:
    digest = hashlib.sha256(host.strip().encode("utf-8")).hexdigest()[:16]
    SSH_CONTROL_SOCKET_ROOT.mkdir(parents=True, exist_ok=True)
    return str(SSH_CONTROL_SOCKET_ROOT / f"{digest}.sock")


def target_alias(target_name: str) -> str:
    clean = target_name.strip()
    if not clean:
        raise ValueError("Target name cannot be empty")
    return clean


def remote_spec(target_name: str, remote_path: str) -> str:
    return f"{target_alias(target_name)}:{remote_path}"


def _split_host_components(host: str) -> tuple[Optional[str], str]:
    clean = host.strip()
    if "@" in clean:
        user, host_name = clean.rsplit("@", 1)
        return user.strip() or None, host_name.strip()
    return None, clean


def _render_target_block(target_name: str, target_cfg: TargetConfig) -> str:
    alias = target_alias(target_name)
    user, host_name = _split_host_components(target_cfg.host)
    lines = [
        f"Host {alias}",
        f"    HostName {host_name}",
    ]
    if user:
        lines.append(f"    User {user}")
    lines.extend(
        [
            "    BatchMode yes",
            f"    ConnectTimeout {SSH_CONNECT_TIMEOUT}",
            "    ControlMaster auto",
            f"    ControlPath {control_socket_path(target_cfg.host)}",
            f"    ControlPersist {SSH_CONTROL_PERSIST}",
        ]
    )
    return "\n".join(lines)


def ensure_ssh_config(project_root: Path, cfg: ProjectConfig) -> Path:
    base_dir = ssh_dir(project_root)
    base_dir.mkdir(parents=True, exist_ok=True)
    SSH_CONTROL_SOCKET_ROOT.mkdir(parents=True, exist_ok=True)

    blocks: list[str] = []
    for target_name in sorted(cfg.targets.keys()):
        target_cfg = cfg.targets[target_name]
        if is_local_transport(target_cfg.transport, target_cfg.host):
            continue
        blocks.append(_render_target_block(target_name, target_cfg))

    config_text = ""
    if blocks:
        config_text = "# Generated by cluster-dispatch\n\n" + "\n\n".join(blocks) + "\n"
    config_file = ssh_config_path(project_root)
    config_file.write_text(config_text)
    return config_file


def ssh_command(
    project_root: Path,
    cfg: ProjectConfig,
    target_name: str,
    target_cfg: TargetConfig,
    *remote_args: str,
    tty: bool = False,
    connect_timeout: Optional[int] = None,
) -> list[str]:
    config_file = ensure_ssh_config(project_root, cfg)
    cmd = ["ssh"]
    if tty:
        cmd.append("-t")
    cmd.extend(["-F", str(config_file)])
    if connect_timeout is not None:
        cmd.extend(["-o", f"ConnectTimeout={int(connect_timeout)}"])
    cmd.append(target_alias(target_name))
    cmd.extend(remote_args)
    return cmd


def rsync_remote_shell(
    project_root: Path,
    cfg: ProjectConfig,
    target_cfg: TargetConfig,
    connect_timeout: Optional[int] = None,
) -> str:
    config_file = ensure_ssh_config(project_root, cfg)
    cmd = ["ssh", "-F", str(config_file)]
    if connect_timeout is not None:
        cmd.extend(["-o", f"ConnectTimeout={int(connect_timeout)}"])
    return shlex.join(cmd)


def rsync_command(
    base_cmd: list[str],
    project_root: Path,
    cfg: ProjectConfig,
    target_name: str,
    target_cfg: TargetConfig,
    connect_timeout: Optional[int] = None,
) -> list[str]:
    if is_local_transport(target_cfg.transport, target_cfg.host):
        return list(base_cmd)
    return [
        base_cmd[0],
        "-e",
        rsync_remote_shell(
            project_root=project_root,
            cfg=cfg,
            target_cfg=target_cfg,
            connect_timeout=connect_timeout,
        ),
        *base_cmd[1:],
    ]


def run_remote_shell(
    project_root: Path,
    cfg: ProjectConfig,
    target_name: str,
    target_cfg: TargetConfig,
    command: str,
    *,
    check: bool = False,
    capture_output: bool = True,
    text: bool = True,
    tty: bool = False,
    input_text: Optional[str] = None,
    stdin_devnull: bool = True,
    connect_timeout: Optional[int] = None,
) -> subprocess.CompletedProcess[str]:
    if is_local_transport(target_cfg.transport, target_cfg.host):
        kwargs = {
            "capture_output": capture_output,
            "text": text,
            "check": check,
        }
        if input_text is not None:
            kwargs["input"] = input_text
        elif stdin_devnull:
            kwargs["stdin"] = subprocess.DEVNULL
        return subprocess.run(["bash", "-lc", command], **kwargs)

    kwargs = {
        "capture_output": capture_output,
        "text": text,
        "check": check,
    }
    if input_text is not None:
        kwargs["input"] = input_text
    elif stdin_devnull:
        kwargs["stdin"] = subprocess.DEVNULL
    return subprocess.run(
        ssh_command(
            project_root=project_root,
            cfg=cfg,
            target_name=target_name,
            target_cfg=target_cfg,
            *[command],
            tty=tty,
            connect_timeout=connect_timeout,
        ),
        **kwargs,
    )
